services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/src/app
  database:
    hostname: database
    image: ankane/pgvector:v0.5.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
      - ./.data/pgdata:/var/lib/postgresql/data
  langfuse:
    image: langfuse/langfuse:2
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/langfuse
      - NEXTAUTH_URL=http://app.localhost
      - NEXTAUTH_SECRET=secret
      - SALT=salt
      - HOSTNAME=0.0.0.0
  webserver:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app